set_temperature:
  name: Set Temperature
  description: Set the target temperature of the Volcano Hybrid.
  target:
    entity:
      integration: volcano_hybrid
      domain: climate
  fields:
    temperature:
      name: Temperature
      description: Target temperature in Celsius.
      required: true
      selector:
        number:
          min: 40
          max: 230
          step: 5
          unit_of_measurement: °C

fan_timer:
  name: Fan Timer
  description: Turn on the fan and set a timer to turn it off after a specified duration.
  target:
    entity:
      integration: volcano_hybrid
  fields:
    duration:
      name: Duration
      description: Duration in seconds before turning off the fan.
      required: true
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    turn_off_heat:
      name: Turn Off Heat
      description: Whether to also turn off the heater when the timer expires.
      required: false
      default: false
      selector:
        boolean:
    turn_off_screen:
      name: Turn Off Screen
      description: Whether to also turn off the screen when the timer expires.
      required: false
      default: false
      selector:
        boolean:

screen_animation:
  name: Screen Animation
  description: Start a screen animation on the Volcano Hybrid.
  target:
    entity:
      integration: volcano_hybrid
  fields:
    animation_type:
      name: Animation Type
      description: Type of animation to start.
      required: true
      selector:
        select:
          options:
            - "none"
            - "blinking"
            - "breathing"
            - "ascending"
            - "descending"
