name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint black
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint with pylint
        run: |
          pylint custom_components/volcano_hybrid
      - name: Check formatting with black
        run: |
          black --check custom_components/volcano_hybrid
